Cross referencing movie with common words
bfbachmann/Silver-Screen pull request #31
Opened 2016-11-09 18:17 UTC by niliur

Added feature for adding "movie" to twitter search when movie title is a common english word

2016-11-09 23:12 UTC, bfbachmann commented on app/models.py
> +            word = word.replace("\n", "")
It seems like this loop does the same thing as the list assignment above it.

2016-11-09 23:23 UTC, bfbachmann requested changes
Definitely needs cleanup and logical fixes before merge. We should not be ignoring movie titles just because they are comprised of multiple words.

2016-11-09 23:23 UTC, bfbachmann commented on app/models.py
> +            word = word.replace("\n", "")
It seems like this loop does the same thing as the list assignment above it.

2016-11-09 23:23 UTC, bfbachmann commented on app/models.py
> +            return False
Does it make sense to return false just because the movie title has multiple words in it? This will almost always be the case.

2016-11-09 23:23 UTC, bfbachmann commented on app/models.py
> +        for word in self.common_wordlist:
This loop can be condensed into a single line: `return (search_term in self.common_wordlist)`

2016-11-09 23:23 UTC, bfbachmann commented on app/models.py
> +            elif (search_term < word):
What is the `<` comparator for here?

2016-11-09 23:23 UTC, bfbachmann commented on scripts/common_word_detector/nppBackup/common_word_detector.py.2016-11-09_000406.bak
> +class word_detector(object):
Why is this file here?

2016-11-09 23:23 UTC, bfbachmann commented on scripts/common_word_detector/nppBackup/common_word_detector.py.2016-11-09_000946.bak
> +class word_detector(object):
Why is this here?

2016-11-09 23:23 UTC, bfbachmann commented on scripts/common_word_detector/nppBackup/common_word_detector.py.2016-11-09_001922.bak
> +class word_detector(object):
Why

2016-11-09 23:23 UTC, bfbachmann commented on scripts/common_word_detector/nppBackup/test.py.2016-11-08_235332.bak
> +import sys
why

2016-11-09 23:23 UTC, bfbachmann commented on scripts/common_word_detector/nppBackup/test.py.2016-11-09_001003.bak
> +from common_word_detector import word_detector
y

2016-11-09 23:23 UTC, bfbachmann commented on scripts/omdb_api/testSample.json
> +{"created_at": "Thu Oct 13 01:47:14 +0000 2016", "favorite_count": 34466, "hashtags": [], "id": 786382757840588804, "id_str": "786382757840588804", "lang": "en", "retweet_count": 16019, "source": "<a
Why?

2016-11-09 23:23 UTC, closed without merging

2016-11-10 09:54 UTC, niliur commented
Oops, should have checked the diff before making the pull request  ><
OK the current analysis is too simplistic, maybe I will add a points system like the sentiment analysis but not as indepth.